### ISSUE TITLE
Allow (or maybe document) binding of arbitrary extra helper programs into `cb-bwrap` chroot

### ISSUE THREAD

**Issue by vidraj** [chewi/cross-boss#2]
I'm using cross-boss to cross-compile a rootfs for a PowerPC platform in conjunction with QEMU-user. My platform requires me to specify the `-cpu` to qemu-ppc when chrooting, otherwise I get illegal instruction errors. To do that, I use a wrapper program that `execve`s QEMU with the `-cpu` parameter added.

What is the best way of binding both the wrapper and QEMU binaries to the target? `cb-bwrap` automatically parses the `binfmt_misc` registry and binds the interpreter it finds there. In my case, it therefore binds the wrapper, but not the actual QEMU executable. As a hack, I added a dummy and otherwise unused entry to `binfmt_misc` containing `qemu-ppc` as the target.

Reading the source code, I see that passing `--ro-bind "${qemu_path}" "${qemu_path}"` as extra arguments to `cb-bwrap` would perhaps also work, but it's not documented. Is that a supported way, or just an implementation detail?

**Comment by chewi** [comment]
When I've had to do this for m68k in the past, I've simply done it by setting the `QEMU_CPU` environment variable. Does that work for you?

**Comment by vidraj** [comment]
I guess it does. The man page for QEMU on my system doesn't mention that option, I'll try it out. Thank you!

**Comment by chewi** [comment]
Great. `qemu-ppc -help` shows the other variables.

**Comment by vidraj** [comment]
OK, I see them there. I just never ran `--help` before, I guess. :-)

Anyway, your suggestion doesn't really work (unless I'm missing something – feel free to correct me, please!), because Portage spawns many processes without passing environment to them, e.g. ldconfig. I guess the build system proper can get the variable if I define it in `/etc/portage/bashrc`, but it feels a bit like a hack, because (at least for me) the point of using cross-boss is to avoid polluting the target filesystem with host-dependent binaries and config. But it doesn't help anyway, because `sandbox` itself only gets a sanitized environment and therefore dies before it can set the env of the build.

For reference, I'm getting the following output:
```
>>> Emerging (1 of 35) sys-devel/autoconf-wrapper-20221207-r1::gentoo
 * autotools-wrappers-at-20221207.tar.gz BLAKE2B SHA512 size ;-) ...     [ ok ]
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
 * The ebuild phase 'unpack' has been killed by signal 4.
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
 * The ebuild phase 'die_hooks' has been killed by signal 4.

>>> Failed to emerge sys-devel/autoconf-wrapper-20221207-r1, Log file:

>>>  '/var/tmp/portage/sys-devel/autoconf-wrapper-20221207-r1/temp/build.log'
```

Strace shows that the dying processes are ldconfig and sandbox.
